version: '3'

services:
  node:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - 3100:3000
    volumes:
      - ./:/app
      - .data/db:/data
    command: ['yarn', 'dev']
    environment:
      - NODE_ENV=development
      - DATA_PATH=/data